language: node_js
cache:
  directories: node_modules
node_js:
  - "9"
  - "8"

install:
  - npm install
  - npm install -g codecov
script:
  - npm run test --findRelatedTests --collectCoverage='false'
after_success:
  - codecov
os:
  - linux
  - osx