language: node_js
cache:
  yarn: true
  directories: node_modules
node_js:
  - "9"
  - "8"

before_install:
  - npm install -g yarn --cache-min 999999999
install:
  - yarn install
  - yarn global add codecov
script:
  - yarn test --findRelatedTests --collectCoverage='false'
  - codecov
os:
  - linux
  - osx