language: node_js
cache:
  yarn: true
  directories: node_modules
node_js:
  - "9"
  - "8"

install:
  - yarn install
  - yarn global add codecov
script:
  - yarn test --findRelatedTests --collectCoverage='false'
  - codecov
os:
  - linux
  - osx